[package]
name = "axelar-message-primitives"
description = "Defines simple primitive data types that wrap around and work with Axelar's message types."
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
alloy-sol-types.workspace = true
bnum.workspace = true
borsh.workspace = true
bytemuck.workspace = true
hex.workspace = true
rkyv = { workspace = true, features = ["validation"] }
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
evm-contracts-rs.workspace = true
evm-contracts-test-suite.workspace = true
hex.workspace = true
rstest.workspace = true
test-log.workspace = true
tokio.workspace = true
