[package]
name = "axelar-solana-multicall"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]

[lints]
workspace = true

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
alloy-sol-types.workspace = true
axelar-executable.workspace = true
borsh.workspace = true
axelar-solana-gateway = { workspace = true, features = ["no-entrypoint"] }
solana-program.workspace = true

[dev-dependencies]
axelar-rkyv-encoding.workspace = true
axelar-solana-memo-program = { workspace = true, features = ["no-entrypoint"] }
axelar-solana-gateway-test-fixtures.workspace = true
ethers-core.workspace = true
evm-contracts-test-suite.workspace = true
itertools.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
test-fixtures.workspace = true
