[package]
name = "axelar-solana-governance"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
solana-program.workspace = true
axelar-executable.workspace = true
program-utils.workspace = true
governance-gmp.workspace = true
borsh.workspace = true
axelar-solana-encoding.workspace = true
alloy-sol-types.workspace = true
base64.workspace = true
axelar-solana-gateway = { workspace = true, features = ["no-entrypoint"] }

[dev-dependencies]
solana-logger.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
ethers.workspace = true
alloy-primitives.workspace = true
axelar-solana-gateway-test-fixtures.workspace = true
axelar-solana-memo-program = { workspace = true, features = ["no-entrypoint"] }
dummy-axelar-solana-gateway = { workspace = true, features = ["no-entrypoint"] }
uuid = { version = "1.11.0", features = ["v4"] }
serde.workspace = true
