[package]
name = "axelar-solana-gateway-test-fixtures"
version = "0.1.0"
edition = "2021"

[dependencies]
axelar-solana-encoding.workspace = true
tokio.workspace = true
solana-program.workspace = true
solana-program-test.workspace = true
bincode.workspace = true
axelar-solana-gateway.workspace = true
axelar-executable.workspace = true
typed-builder.workspace = true
solana-sdk.workspace = true
ed25519-dalek = { workspace = true, features = ["rand_core", "digest"] }
libsecp256k1.workspace = true
rand.workspace = true
libsecp-rand.workspace = true
gateway-event-stack.workspace = true
axelar-solana-gas-service.workspace = true
spl-token-2022 = { workspace = true, features = ["no-entrypoint"] }
spl-associated-token-account = { workspace = true, features = ["no-entrypoint"] }

solana-test-validator = { workspace = true }
solana-rpc-client-api = { workspace = true }


[lints]
workspace = true
