name: Run Axelar Chains Config Tests

on: pull_request

jobs:
  test:
    runs-on: blacksmith-2vcpu-ubuntu-2204

    steps:
      - name: Install Node.js
        uses: useblacksmith/setup-node@v5
        with:
          node-version: 18.x
          cache: 'npm'

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install
        run: npm ci
        working-directory: axelar-chains-config

      - name: Test
        run: npm run test
        working-directory: axelar-chains-config
