[package]
name = "axelar-solana-gateway"
version = "0.1.0"
edition = "2021"

[lints.rust]
missing_docs = "warn"
rust_2018_idioms = "deny"
unreachable_pub = "warn"
unused_imports = "warn"
unused_must_use = "deny"

[lib]
crate-type = ["cdylib", "lib"]

[features]
no-entrypoint = []
test-sbf = []

[dependencies]
axelar-message-primitives.workspace = true
axelar-solana-encoding = { workspace = true, features = ["solana"] }
bincode.workspace = true
bitvec.workspace = true
borsh.workspace = true
bytemuck.workspace = true
ed25519-dalek.workspace = true
hex.workspace = true
itertools.workspace = true
libsecp256k1.workspace = true
num-derive.workspace = true
num-traits.workspace = true
program-utils.workspace = true
solana-program.workspace = true
thiserror.workspace = true

[dev-dependencies]
hex.workspace = true
lazy_static.workspace = true
sha3.workspace = true
solana-client.workspace = true
solana-logger.workspace = true
solana-program-test.workspace = true
solana-sdk.workspace = true
rand.workspace = true
typed-builder.workspace = true
axelar-solana-gateway-test-fixtures.workspace = true
rstest.workspace = true
pretty_assertions.workspace = true
